import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import { Fredoka } from "next/font/google";
import Navbar from "@/components/ui/Navbar";

const fredoka = Fredoka({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-fredoka",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body
        className={`${fredoka.className}  min-h-screen my-0 mx-auto max-w-[120rem] bg-backgroundColor`}
      >
        <div>{children}</div>
        <Toaster />
      </body>
    </html>
  );
}
